<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>scopeName</key>
    <string>source.sleet</string>
    <key>name</key>
    <string>Sleet</string>
    <key>fileTypes</key>
    <array>
        <string>sleet</string>
    </array>
    <key>patterns</key>
    <array>
        <dict>
            <key>name</key>
            <string>comment.line.shebang.sleet</string>
            <key>match</key>
            <string>^#!\s*(.*)$</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(\s*)#\.\s*$</string>
            <key>end</key>
            <string>^(?!\1\s+|$)</string>
            <key>name</key>
            <string>comment.block.sleet</string>
        </dict>
        <dict>
            <key>match</key>
            <string>^\s*#\s+(.*)$</string>
            <key>name</key>
            <string>comment.line.sleet</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(\s*)\|\.\s*$</string>
            <key>end</key>
            <string>^(?!\1\s+|$)</string>
            <key>comment</key>
            <string>pipeline text block</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.sleet</string>
                </dict>
            </dict>
        </dict>
        <dict>
            <key>match</key>
            <string>^(\s*)\|\s+.*$</string>
            <key>comment</key>
            <string>pipeline text</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#script</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#style</string>
        </dict>
        <dict>
            <key>begin</key>
            <string>^(\s*)([\w$@_-]*)(([.#][\w$@_-]*)*)(?=.*\s*\.\s*$)</string>
            <key>beginCaptures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.sleet</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.attribute-name.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>^(?!(\1\s)|\s*$)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#line-end-with-dot</string>
                </dict>
            </array>
        </dict>
        <dict>
            <key>include</key>
            <string>#tag</key>
        </dict>
        <dict>
            <key>include</key>
            <string>#attribute</key>
        </dict>
        <dict>
            <key>match</key>
            <string>(?<=\S)\s+.*$</string>
            <key>comment</key>
            <string>inline text</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>line-end-with-dot</key>
        <dict>
            <key>begin</key>
            <string>\G</string>
            <key>end</key>
            <string>\.\s*$</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#tag</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#attribute</string>
                </dict>
            </array>
        </dict>
        <key>tag</key>
        <dict>
            <key>match</key>
            <string>(^\s*|\s*[:<>+]\s*)([\w$@_-]*)(([.#][\w$@_-]+)*)</string>
            <key>captures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.sleet</string>
                </dict>
                <key>3</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.attribute-name.sleet</string>
                </dict>
            </dict>
        </dict>
        <key>attribute</key>
        <dict>
            <key>begin</key>
            <string>(&\w+)?\(</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.attribute.start.sleet</string>
                </dict>
                <key>1</key>
                <dict>
                    <key>name</key>
                    <string>entity.other.attribute-name.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>\)</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.attribute.start.sleet</string>
                </dict>
            </dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>'[^']*'|"[^"]*"</string>
                    <key>name</key>
                    <string>string.quoted.sleet</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[=+]</string>
                    <key>name</key>
                    <string>punctuation.definition.attribute.start.sleet</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b[0-9]+\b</string>
                    <key>name</key>
                    <string>constant.numeric.sleet</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>\b(true|false)\b</string>
                    <key>name</key>
                    <string>constant.language.boolean.sleet</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>[^\s()'"=+]+</string>
                    <key>name</key>
                    <string>entity.other.attribute-name.sleet</string>
                </dict>
            </array>
        </dict>
        <key>script</key>
        <dict>
            <key>begin</key>
            <string>(\s*)(script)(?=.*\.\s*$)</string>
            <key>beginCaptures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>^(?!(\1\s)|\s*$)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#line-end-with-dot</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.js</string>
                </dict>
            </array>
        </dict>
        <key>style</key>
        <dict>
            <key>begin</key>
            <string>(\s*)(style)(?=.*\.\s*$)</string>
            <key>beginCaptures</key>
            <dict>
                <key>2</key>
                <dict>
                    <key>name</key>
                    <string>entity.name.tag.sleet</string>
                </dict>
            </dict>
            <key>end</key>
            <string>^(?!(\1\s)|\s*$)</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>include</key>
                    <string>#line-end-with-dot</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>source.css</string>
                </dict>
            </array>
        </dict>
    </dict>
</dict>
</plist>
